import { z } from 'zod'

export const zSchema = z.object({
    email: z.string().email({ message: "Invalid email address" }).optional(),
    password: z.string().optional(),
    name: z.string().min(2, { message: "Name must be at least 2 characters" }).max(50, { message: "Name must be at most 50 characters" }),
    phone: z.string().regex(/^[6-9]\d{9}$/, { message: "Enter a valid 10-digit Indian mobile number" }),
    otp: z.union([z.string().regex(/^\d{6}$/), z.number().int().min(100000).max(999999)]).transform(val => String(val)),
    sellerType: z.enum(['thrift_seller', 'brand_seller'], { message: "Seller type must be either thrift_seller or brand_seller" }),
    storeName: z.string().min(3, 'Store name must be at least 3 characters').optional(),
    storeDescription: z.string().optional(),
    _id: z.string().min(3).optional(),
    alt: z.string().optional(),
    title: z.string().optional(),
    slug: z.string().min(3).optional(),
    category: z.string().min(3).optional(),
    mrp: z.union([z.number().positive(), z.string().transform(val => Number(val))]).optional(),
    sellingPrice: z.union([z.number().positive(), z.string().transform(val => Number(val))]).optional(),
    discountPercentage: z.union([z.number(), z.string().transform(val => Number(val))]).optional(),
    description: z.string().optional(),
    media: z.array(z.string()).optional(),
    product: z.string().optional(),
    color: z.string().optional(),
    size: z.string().optional(),
    sku: z.string().optional(),
    uniqueCode: z.string().optional(),
    condition: z.enum(['like_new', 'excellent', 'good', 'fair']).optional(),
    productType: z.enum(['thrift', 'brand_new']).optional(),
    code: z.string().optional(),
    amount: z.union([z.number().positive(), z.string().transform(val => Number(val))]).optional(),
    minShoppingAmount: z.union([z.number().positive(), z.string().transform(val => Number(val))]).optional(),
    validity: z.coerce.date().optional(),
    userId: z.string().optional(),
    rating: z.union([z.number(), z.string().transform(val => Number(val))]).optional(),
    review: z.string().optional(),
    country: z.string().optional(),
    state: z.string().optional(),
    city: z.string().optional(),
    pincode: z.string().optional(),
    landmark: z.string().optional(),
    ordernote: z.string().optional(),
    address: z.string().optional(),
})